.gitlab-ci.yml:
  unmanaged: true
.rspec:
  unmanaged: true
.travis.yml:
  unmanaged: true
.rubocop.yml:
  unmanaged: true
Gemfile:
  unmanaged: true
  # This nonsense makes pdk new provider work
  optional:
    ':development':
      - gem: 'puppet-resource_api'
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ':rspec'
